apiVersion: apps/v1
kind: Deployment
metadata:
  name: minor-app
  labels:
    app: minor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minor
  template:
    metadata:
      labels:
        app: minor
    spec:
      containers:
        - name: minor
          image: manav108/minor:latest
          ports:
            - containerPort: 8501