apiVersion: apps/v1
kind: Deployment
metadata:
  name: species-recognition
spec:
  replicas: 2
  selector:
    matchLabels:
      app: species-recognition
  template:
    metadata:
      labels:
        app: species-recognition
    spec:
      containers:
      - name: species-recognition
        image: your-registry/species-recognition:latest
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: model-pvc