name: Deploy to EC2 via Docker

on:
  push:
    branches:
      - main  # Deploy only when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract GitHub commit hash
        id: vars
        run: echo "GITHUB_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/minor:${{ env.GITHUB_SHA }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/minor:${{ env.GITHUB_SHA }}

      - name: SSH into EC2 and deploy container
        uses: appleboy/ssh-action@v0.1.12
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/minor:${{ env.GITHUB_SHA }}
            docker stop minor || true
            docker rm minor || true
            docker run -d --name minor -p 80:80 ${{ secrets.DOCKER_USERNAME }}/minor:${{ env.GITHUB_SHA }}
