name: Deploy to EC2 via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: vars
        run: echo "GITHUB_SHA=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/minor:${{ env.GITHUB_SHA }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/minor:${{ env.GITHUB_SHA }}

      - uses: leangen/action-ssh@v0.11.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/minor:${{ env.GITHUB_SHA }}
            docker stop minor || true
            docker rm minor || true
            docker run -d --name minor -p 80:80 ${{ secrets.DOCKER_USERNAME }}/minor:${{ env.GITHUB_SHA }}